_root.Paused = false;
_root.Score = 0;
_root.current_map_num = 1;
score_increment_amount = 50;
start_delays_array = new Array(240,220,200,180,160,140,120,100);
_root.Score = 0;
_root.lives_remaining = 3;
number_of_levels = 8;
num_cars_array = new Array(4,4,5,5,6,6,7,7);
_root.turbo_speed = 3;
_root.normal_speed = 1;
_root.train_speed = _root.normal_speed;
_root.number_of_segment_types = 9;
_root.segment_orig_array = new Array(0,1,2,3,4,5,6,7,8);
_root.segment_temp_array = _root.segment_orig_array;
segment_names_array = new Array("track_curve_1_MC","track_curve_2_MC","track_curve_3_MC","track_curve_4_MC","track_crossing_MC","track_duo_curves_1_MC","track_duo_curves_2_MC","track_straight_horiz_MC","track_straight_vert_MC");
_root.LoadSound("coin");
_root.LoadSound("end_riff");
_root.LoadSound("harp_blast");
_root.LoadSound("game_loop");
_root.LoadSound("lay_track_sound");
_root.LoadSound("bomb_sound");
_root.LoadSound("no_drop_sound");
_root.LoadSound("crash_sound");
_root.LoadSound("steam_sound");
out_of_lives_text = "No lives left \n game over!";
lost_life_text = "Train crashed! \n Lose a life";
_root.steam_sound.start(0,1);
